In [ ]:
import numpy as np

In [ ]:
import tensorflow as tf
from tensorflow import  keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [ ]:
df = pd.DataFrame ({
    "soil_moisture": [0.10,0.15,0.20,0.25,0.40,0.60,0.35,0.18,
                      0.45,0.05,0.80,0.27,0.55,0.70,0.12,0.30],
    "Temperature_c": [34,30,26,22,28,30,19,22,35,24,32,21,25,30,23,40],
    "sun_lights_Hours": [5,8,7,8,10,3,10,12,5,9,11,2,6,1,9,12],
    "needs_water": [1,1,1,0,0,0,0,1,0,1,0,1,0,0,1,1]
})

In [ ]:
df

    soil_moisture  Temperature_c  sun_lights_Hours  needs_water
0            0.10             34                 5            1
1            0.15             30                 8            1
2            0.20             26                 7            1
3            0.25             22                 8            0
4            0.40             28                10            0
5            0.60             30                 3            0
6            0.35             19                10            0
7            0.18             22                12            1
8            0.45             35                 5            0
9            0.05             24                 9            1
10           0.80             32                11            0
11           0.27             21                 2            1
12           0.55             25                 6            0
13           0.70             30                 1            0
14           0.12             23                 9            1
15           0.30             40                12            1

In [ ]:
x = df[['soil_moisture','Temperature_c','sun_lights_Hours']]
y = df['needs_water']

In [ ]:
x

    soil_moisture  Temperature_c  sun_lights_Hours
0            0.10             34                 5
1            0.15             30                 8
2            0.20             26                 7
3            0.25             22                 8
4            0.40             28                10
5            0.60             30                 3
6            0.35             19                10
7            0.18             22                12
8            0.45             35                 5
9            0.05             24                 9
10           0.80             32                11
11           0.27             21                 2
12           0.55             25                 6
13           0.70             30                 1
14           0.12             23                 9
15           0.30             40                12

In [ ]:
# normalization
# min max

x_min = x.min()
x_max = x.max()
x_scaled = (x - x_min) / (x_max - x_min + 1e-8)

In [ ]:
x_scaled

    soil_moisture  Temperature_c  sun_lights_Hours
0        0.066667       0.714286          0.363636
1        0.133333       0.523810          0.636364
2        0.200000       0.333333          0.545455
3        0.266667       0.142857          0.636364
4        0.466667       0.428571          0.818182
5        0.733333       0.523810          0.181818
6        0.400000       0.000000          0.818182
7        0.173333       0.142857          1.000000
8        0.533333       0.761905          0.363636
9        0.000000       0.238095          0.727273
10       1.000000       0.619048          0.909091
11       0.293333       0.095238          0.090909
12       0.666667       0.285714          0.454545
13       0.866667       0.523810          0.000000
14       0.093333       0.190476          0.727273
15       0.333333       1.000000          1.000000

In [ ]:
x_train, x_test,y_train, y_test =  train_test_split(x_scaled,y,test_size = 0.25 , random_state = 42)

In [ ]:
model = keras.Sequential([
    layers.Input(shape = (x_train.shape[1],)),          # input layer
    layers.Dense(8,activation= 'relu'),                   # hidden layer
    layers.Dense(1,activation = 'sigmoid')                   # output layer
])

In [ ]:
model.compile(optimizer= 'sgd', loss = 'binary_crossentropy',metrics = ['accuracy'])

In [ ]:
history = model.fit(
    x_train.values, y_train.values,
    validation_data = (x_test.values,y_test.values),
    epochs =  100,batch_size = 4 , verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6950 - val_accuracy: 0.2500 - val_loss: 0.7712
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5833 - loss: 0.6947 - val_accuracy: 0.2500 - val_loss: 0.7717
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6938 - val_accuracy: 0.2500 - val_loss: 0.7722
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6939 - val_accuracy: 0.2500 - val_loss: 0.7727
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6935 - val_accuracy: 0.2500 - val_loss: 0.7731
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6930 - val_accuracy: 0.2500 - val_loss: 0.7736
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6927 - val_accuracy: 0.2500 - val_loss: 0.7741
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6925 - val_accuracy: 0.2500 - val_loss: 0.7745
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6926 - val_accuracy: 0.2500 - val_loss: 0.7750
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6920 - val_accuracy: 0.2500 - val_loss: 0.7754
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6924 - val_accuracy: 0.2500 - val_loss: 0.7758
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6916 - val_accuracy: 0.2500 - val_loss: 0.7763
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6920 - val_accuracy: 0.2500 - val_loss: 0.7767
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6910 - val_accuracy: 0.2500 - val_loss: 0.7771
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6908 - val_accuracy: 0.2500 - val_loss: 0.7775
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5833 - loss: 0.6911 - val_accuracy: 0.2500 - val_loss: 0.7779
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6907 - val_accuracy: 0.2500 - val_loss: 0.7783
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6904 - val_accuracy: 0.2500 - val_loss: 0.7787
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6900 - val_accuracy: 0.2500 - val_loss: 0.7791
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6900 - val_accuracy: 0.2500 - val_loss: 0.7795
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6896 - val_accuracy: 0.2500 - val_loss: 0.7799
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6897 - val_accuracy: 0.2500 - val_loss: 0.7802
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6899 - val_accuracy: 0.2500 - val_loss: 0.7806
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6890 - val_accuracy: 0.2500 - val_loss: 0.7810
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6895 - val_accuracy: 0.2500 - val_loss: 0.7812
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5833 - loss: 0.6893 - val_accuracy: 0.2500 - val_loss: 0.7815
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6885 - val_accuracy: 0.2500 - val_loss: 0.7818
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6896 - val_accuracy: 0.2500 - val_loss: 0.7821
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6882 - val_accuracy: 0.2500 - val_loss: 0.7823
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6882 - val_accuracy: 0.2500 - val_loss: 0.7826
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6881 - val_accuracy: 0.2500 - val_loss: 0.7828
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6876 - val_accuracy: 0.2500 - val_loss: 0.7831
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6875 - val_accuracy: 0.2500 - val_loss: 0.7833
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6873 - val_accuracy: 0.2500 - val_loss: 0.7836
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6871 - val_accuracy: 0.2500 - val_loss: 0.7838
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6870 - val_accuracy: 0.2500 - val_loss: 0.7840
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6868 - val_accuracy: 0.2500 - val_loss: 0.7843
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6873 - val_accuracy: 0.2500 - val_loss: 0.7845
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6865 - val_accuracy: 0.2500 - val_loss: 0.7847
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6869 - val_accuracy: 0.2500 - val_loss: 0.7849
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6863 - val_accuracy: 0.2500 - val_loss: 0.7851
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6861 - val_accuracy: 0.2500 - val_loss: 0.7853
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6859 - val_accuracy: 0.2500 - val_loss: 0.7855
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6858 - val_accuracy: 0.2500 - val_loss: 0.7857
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6863 - val_accuracy: 0.2500 - val_loss: 0.7859
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6854 - val_accuracy: 0.2500 - val_loss: 0.7861
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6854 - val_accuracy: 0.2500 - val_loss: 0.7863
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6852 - val_accuracy: 0.2500 - val_loss: 0.7865
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6851 - val_accuracy: 0.2500 - val_loss: 0.7866
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6853 - val_accuracy: 0.2500 - val_loss: 0.7868
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6852 - val_accuracy: 0.2500 - val_loss: 0.7870
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6849 - val_accuracy: 0.2500 - val_loss: 0.7871
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6846 - val_accuracy: 0.2500 - val_loss: 0.7873
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6851 - val_accuracy: 0.2500 - val_loss: 0.7875
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6844 - val_accuracy: 0.2500 - val_loss: 0.7876
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6848 - val_accuracy: 0.2500 - val_loss: 0.7878
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5833 - loss: 0.6844 - val_accuracy: 0.2500 - val_loss: 0.7879
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6839 - val_accuracy: 0.2500 - val_loss: 0.7881
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6838 - val_accuracy: 0.2500 - val_loss: 0.7882
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6841 - val_accuracy: 0.2500 - val_loss: 0.7884
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6841 - val_accuracy: 0.2500 - val_loss: 0.7885
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5833 - loss: 0.6834 - val_accuracy: 0.2500 - val_loss: 0.7886
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6836 - val_accuracy: 0.2500 - val_loss: 0.7888
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6831 - val_accuracy: 0.2500 - val_loss: 0.7889
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6830 - val_accuracy: 0.2500 - val_loss: 0.7890
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6833 - val_accuracy: 0.2500 - val_loss: 0.7891
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5833 - loss: 0.6828 - val_accuracy: 0.2500 - val_loss: 0.7892
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6826 - val_accuracy: 0.2500 - val_loss: 0.7893
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5833 - loss: 0.6826 - val_accuracy: 0.2500 - val_loss: 0.7895
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6824 - val_accuracy: 0.2500 - val_loss: 0.7896
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5833 - loss: 0.6823 - val_accuracy: 0.2500 - val_loss: 0.7897
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5833 - loss: 0.6829 - val_accuracy: 0.2500 - val_loss: 0.7898
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6827 - val_accuracy: 0.2500 - val_loss: 0.7899
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5833 - loss: 0.6823 - val_accuracy: 0.2500 - val_loss: 0.7900
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6825 - val_accuracy: 0.2500 - val_loss: 0.7901
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6818 - val_accuracy: 0.2500 - val_loss: 0.7902
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5833 - loss: 0.6816 - val_accuracy: 0.2500 - val_loss: 0.7902
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5833 - loss: 0.6822 - val_accuracy: 0.2500 - val_loss: 0.7903
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5833 - loss: 0.6814 - val_accuracy: 0.2500 - val_loss: 0.7904
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5833 - loss: 0.6813 - val_accuracy: 0.2500 - val_loss: 0.7905
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.6815 - val_accuracy: 0.2500 - val_loss: 0.7906
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.6812 - val_accuracy: 0.2500 - val_loss: 0.7905
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6815 - val_accuracy: 0.2500 - val_loss: 0.7905
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5833 - loss: 0.6807 - val_accuracy: 0.2500 - val_loss: 0.7905
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6805 - val_accuracy: 0.2500 - val_loss: 0.7905
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6803 - val_accuracy: 0.2500 - val_loss: 0.7904
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6801 - val_accuracy: 0.2500 - val_loss: 0.7904
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6798 - val_accuracy: 0.2500 - val_loss: 0.7904
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6803 - val_accuracy: 0.2500 - val_loss: 0.7903
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5833 - loss: 0.6797 - val_accuracy: 0.2500 - val_loss: 0.7903
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5833 - loss: 0.6792 - val_accuracy: 0.2500 - val_loss: 0.7903
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6790 - val_accuracy: 0.2500 - val_loss: 0.7902
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6788 - val_accuracy: 0.2500 - val_loss: 0.7901
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.6786 - val_accuracy: 0.2500 - val_loss: 0.7901
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6788 - val_accuracy: 0.2500 - val_loss: 0.7899
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6781 - val_accuracy: 0.2500 - val_loss: 0.7898
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6776 - val_accuracy: 0.2500 - val_loss: 0.7896
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6776 - val_accuracy: 0.2500 - val_loss: 0.7895
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6769 - val_accuracy: 0.2500 - val_loss: 0.7893
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6766 - val_accuracy: 0.2500 - val_loss: 0.7892