In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'city': ['Varasnasi','Delhi','Patna','Supaul','Bgp']
})

In [4]:
df

        city
0  Varasnasi
1      Delhi
2      Patna
3     Supaul
4        Bgp

In [7]:
# one hot encoded
encoded = pd.get_dummies(df['city'])

In [8]:
print(encoded)

     Bgp  Delhi  Patna  Supaul  Varasnasi
0  False  False  False   False       True
1  False   True  False   False      False
2  False  False   True   False      False
3  False  False  False    True      False
4   True  False  False   False      False

In [10]:
encoded.astype(int)

   Bgp  Delhi  Patna  Supaul  Varasnasi
0    0      0      0       0          1
1    0      1      0       0          0
2    0      0      1       0          0
3    0      0      0       1          0
4    1      0      0       0          0